---
- name: Install TimescaleDB Postgresql
  hosts: localhost
  become: true
  tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
    - name: Add package epel-release
      yum:
        name:
          - epel-release
        state: present
    - name: Add package pgdg rpm
      yum:
        name:
          - https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
    - name: copy timescaledb repo
      template: src=timescaledb.repo dest=/etc/yum.repos.d/timescale_timescaledb.repo
    - name: update all packages
        yum:
          name: '*'
          state: latest
          exclude: kernel*
    - name: Add package epel-release
        yum:
          name:
            - timescaledb-postgresql-12
          state: present
    