---
- name: Install TimescaleDB Postgresql
  hosts: localhost
  become: true
  vars_prompt:
    - name: "ip"
      prompt: "Entrer votre ip"
      private: no
  tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
    - name: Add package epel-release
      yum:
        name:
          - epel-release
        state: present
    - name: Add package pgdg rpm
      yum:
        name:
          - https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
    - name: copy timescaledb repo
      template: src=timescaledb.repo dest=/etc/yum.repos.d/timescale_timescaledb.repo
    - name: update all packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
    - name: Add package timescaledb package
      yum:
        name:
          - timescaledb-postgresql-12
        state: present
    - name: check if postgresql data directory exist
      stat: path=/var/lib/pgsql/12/data
      register: p
    - name: Recursively change ownership of a directory
      file:
        path: /var/lib/pgsql/12/data
        state: directory
        recurse: yes
        owner: postgres
        group: postgres
      when: not p.stat.exists
    - name: run initdb
      become_user: postgres
      command: /usr/pgsql-12/bin/initdb -D /var/lib/pgsql/12/data
      when: not p.stat.exists
    - name: Replace postgresql config list addresses
      become_user: postgres
      lineinfile:
        path: /var/lib/pgsql/12/data/postgresql.conf
        regexp: "^#listen_addresses = 'localhost'         # what IP address(es) to listen on; "
        insertafter: '^#listen_addresses'
        line: "listen_addresses = '*' "
        backup: yes
    - name: setup preload library
      become_user: postgres
      lineinfile:
        path: /var/lib/pgsql/12/data/postgresql.conf
        regexp: "^#shared_preload_libraries = ''  # (change requires restart)"
        insertafter: '^#shared_preload_libraries'
        line: "shared_preload_libraries = 'timescaledb' "
        backup: yes
    - name: setup public ip address in pg_hba.conf
      become_user: postgres
      lineinfile:
        path: /var/lib/pgsql/12/data/pg_hba.conf
        regexp: '^# IPv4 '
        insertafter: '^# IPv4 '
        line: 'host all all {{ip}}/32 md5'
        backup: yes
    - name: Start postgresql service
      service:
        name: postgresql-12
        state: started

